name: Compartir datos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        run: actions/setup-dotnet@v2
        with:
            donet-version: 6.0.x
      - name: Restore dependencies
        #run: |dotnet restore src/wpm-api/WisdomPetMedicine.sln
      - name: Publish
        run: dotnet publish src/wpm-api/WisdomPetMedicine.sln --configuration Release --output publish
      - name: Subir datos
        uses: actions/upload-artifact@v3
        with:
          path: publish
  storage:
    name: Almacenamiento
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Descargar datos
      uses: actions/downsload-artifact@v3
      with:
        path: publish
    - name: Muestra el contenido del artefacto
      shell: bash
      run: ls publish -R
